/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tree.glb')

  // to spin
  useFrame ( ()=> (group.current.rotation.y += 0.01))

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <mesh geometry={nodes.cgaxis_models_67_31_03.geometry} material={materials.cgaxis_models_67_31_030} position={[-28.86, -10.43, 0]} scale={25.4} />
        <mesh geometry={nodes.cgaxis_models_67_31_02.geometry} material={materials.cgaxis_models_67_31_020} position={[-28.77, -10.36, 0]} scale={25.4} />
        <mesh geometry={nodes.cgaxis_models_67_31_01.geometry} material={materials.cgaxis_models_67_31_010} position={[-28.8, -10.44, 0]} scale={25.4} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree.glb')
